{"error": null, "issues": [{"address": 2652, "code": "&& rollUnder <= MAX_ROLL_UNDER, \"R", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/temp/Wagerwar-0.sol", "function": "placeGame(uint256,uint256,uint256,bytes32,bytes32,address)", "lineno": 105, "title": "Unchecked CALL return value", "type": "Informational"}, {"address": 4543, "code": "rofit = inviteProfits[msg.sender];\n   ", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0xfffffffffffffffffffffffffffffffe00\ncalldata_DiceGame_0: 0x3032b3a700000000000000000000000000000000000000000000000000000000\ncalldatasize_DiceGame: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `withdrawInvitationProfit()`.\nThe subtraction may result in a value < 0.", "filename": "/temp/Wagerwar-0.sol", "function": "withdrawInvitationProfit()", "lineno": 174, "title": "Integer Underflow", "type": "Warning"}], "success": true}
