{"error": null, "issues": [{"address": 3093, "debug": "callvalue: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_6: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldatasize_Slugroad: 0x3\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Slugroad-0.sol", "function": "fallback", "lineno": 597, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3106, "debug": "The exception is triggered under the following conditions:\n\nstorage_6: 0x1\ncallvalue: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldatasize_Slugroad: 0x3\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Slugroad-0.sol", "function": "fallback", "lineno": 597, "title": "Exception state", "type": "Informational"}, {"address": 5489, "code": "erspeed\n    // Reward = HYPERSPEED_L", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/temp/Slugroad-0.sol", "function": "PayThrone()", "lineno": 448, "title": "Message call to external contract", "type": "Informational"}], "success": true}
