{"error": null, "issues": [{"address": 1282, "code": "0; i < _", "debug": "The exception is triggered under the following conditions:\n\nstorage_0: 0x20\ncalldata_StrikersMetadata_0: 0xc87b56dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_StrikersMetadata: 0x4\nmem_192 +\n32 +\n32*\nConcat(0,\n       Extract(255,\n               5,\n               31 +\n               Concat(0,\n                      ~(~Extract(255,\n                                 1,\n                                 115792089237316195423570985008687907853269984665640564039457584007913129639935 +\n                                 256*\n                                 If(Extract(0, 0, storage_0) ==\n                                    0,\n                                    1,\n                                    0)) |\n                        ~Extract(255, 1, storage_0))))): 0x0\ncalldata_StrikersMetadata_4: 0x0\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/CryptoStrikers-2.sol", "function": "tokenURI(uint256)", "lineno": 34, "title": "Exception state", "type": "Informational"}, {"address": 1466, "code": "ing(bab)", "debug": "The exception is triggered under the following conditions:\n\nmem_192 +\n32 +\n32*\nConcat(0,\n       Extract(255,\n               5,\n               31 +\n               Concat(0,\n                      ~(~Extract(255,\n                                 1,\n                                 115792089237316195423570985008687907853269984665640564039457584007913129639935 +\n                                 256*\n                                 If(Extract(0, 0, storage_0) ==\n                                    0,\n                                    1,\n                                    0)) |\n                        ~Extract(255, 1, storage_0))))): 0x1\nstorage_0: 0x2\ncalldata_StrikersMetadata_0: 0xc87b56dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_StrikersMetadata: 0x4\ncalldata_StrikersMetadata_4: 0x0\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/CryptoStrikers-2.sol", "function": "tokenURI(uint256)", "lineno": 35, "title": "Exception state", "type": "Informational"}], "success": true}
