{"error": null, "issues": [{"address": 6483, "code": "= newFromVal;\n   ", "debug": "calldata_shareRecipient_32 + 36: 0xeb7e3000000000012000200134010f94023a7a28e10000000bffefc46000b0f0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_32_+_4: 0x18a3d0000000003d83b1202da8090f2e6802400af2000000280000127fe43efa\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_4: 0xeb7e3000000000012000200134010f94023a7a28e10000000bffefc46000b0f0\ncalldata_shareRecipient_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xeb7e3000000000012000200134010f94023a7a28e10000000bffefc46000b0f0\ncalldata_shareRecipient_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_shareRecipient: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/EtherOnline-16.sol", "function": "transferFrom(address,address,uint256)", "lineno": 169, "title": "Integer Overflow ", "type": "Warning"}, {"address": 6496, "code": "es[_to] = newToVal;\n\n       ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_shareRecipient_32 + 36: 0x7ffffffffffffffffffffffffffffffffffffffffffffffefffffffffffd78b6\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_32_+_4: 0xfffffffffffffffffffffffffffffffebffffffffffffffffffffffe000045de\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_4: 0x7ffffffffffffffffffffffffffffffffffffffffffffffefffffffffffd78b6\ncalldata_shareRecipient_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x7ffffffffffffffffffffffffffffffffffffffffffffffefffffffffffd78b6\ncalldata_shareRecipient_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_shareRecipient: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/EtherOnline-16.sol", "function": "transferFrom(address,address,uint256)", "lineno": 170, "title": "Exception state", "type": "Informational"}, {"address": 6794, "code": "ex]] = index;\n         ", "debug": "calldata_shareRecipient_32 + 36: 0x7\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_32_+_4: 0x3\nstorage_9: 0x0\ncalldata_shareRecipient_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_shareRecipient_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x7\ncalldata_shareRecipient_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_shareRecipient: 0x4\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_4: 0x7\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `transferFrom(address,address,uint256)`.\nThe subtraction may result in a value < 0.", "filename": "/temp/EtherOnline-16.sol", "function": "transferFrom(address,address,uint256)", "lineno": 177, "title": "Integer Underflow", "type": "Warning"}, {"address": 6819, "code": "th -= 1; \n        }\n\n  ", "debug": "The exception is triggered under the following conditions:\n\nstorage_9: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_4: 0x8\ncalldata_shareRecipient_32 + 36: 0x8\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_32_+_4: 0x1\ncalldata_shareRecipient_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_shareRecipient_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x8\ncalldata_shareRecipient_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_shareRecipient: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/EtherOnline-16.sol", "function": "transferFrom(address,address,uint256)", "lineno": 180, "title": "Exception state", "type": "Informational"}, {"address": 7261, "code": "==================", "debug": "storage_9: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_shareRecipient_32 + 36: 0x2\ncalldata_shareRecipient_4: 0x0\ncalldata_shareRecipient_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x2\ncalldata_shareRecipient_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_shareRecipient: 0x4\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_32_+_4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_shareRecipient_4: 0x2\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/EtherOnline-16.sol", "function": "transferFrom(address,address,uint256)", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}], "success": true}
