{"error": null, "issues": [{"address": 3537, "code": "blic{\n\t\trequire(_app != addre", "debug": "The exception is triggered under the following conditions:\n\ncalldata_WarshipMain_4: 0x0\nstorage_2: 0x0\ncalldata_WarshipMain_0: 0x2075d28400000000000000000000000000000000000000000000000000000000\ncalldatasize_WarshipMain: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Warship-5.sol", "function": "_function_0x2075d284", "lineno": 117, "title": "Exception state", "type": "Informational"}, {"address": 4557, "code": "/Used internally insid", "debug": "The exception is triggered under the following conditions:\n\ncalldata_WarshipMain_4: 0x0\nstorage_3: 0x0\ncalldata_WarshipMain_0: 0x6a0970b500000000000000000000000000000000000000000000000000000000\ncalldatasize_WarshipMain: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Warship-5.sol", "function": "_function_0x6a0970b5", "lineno": 175, "title": "Exception state", "type": "Informational"}], "success": true}
