{"error": null, "issues": [{"address": 458, "code": ").balance);\n        return res;\n    }\n", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/temp/Giftomon-3.sol", "function": "withdrawBalance()", "lineno": 29, "title": "Unchecked CALL return value", "type": "Informational"}], "success": true}
