{"error": null, "issues": [{"address": 1201, "code": "**\n   * @dev Divid", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Maths_0: 0xe39bbf6800000000000000000000000000000000000000000000000000000000\ncalldatasize_Maths: 0x4\ncalldata_Maths_32 + 4: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Mythereum-0.sol", "function": "dividedBy(uint256,uint256)", "lineno": 77, "title": "Exception state", "type": "Informational"}, {"address": 1294, "code": "**\n   * @dev Multiplies two factors,", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Maths_4: 0x7fffffffffff800040010000000000000000000000000000000000003f3f0100\ncalldata_Maths_32 + 4: 0xa7ebe09e8686d3e9bb0e6f9b56b30684dc8f0bedbcbd745ffba1528e704040\ncalldata_Maths_0: 0xc8a4ac9c00000000000000000000000000000000000000000000000000000000\ncalldatasize_Maths: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Mythereum-0.sol", "function": "mul(uint256,uint256)", "lineno": 50, "title": "Exception state", "type": "Informational"}, {"address": 1361, "code": "\n    difference = minuend - s", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Maths_4: 0x0\ncalldata_Maths_32 + 4: 0x1\ncalldata_Maths_0: 0xf4f3bdc100000000000000000000000000000000000000000000000000000000\ncalldatasize_Maths: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Mythereum-0.sol", "function": "minus(uint256,uint256)", "lineno": 31, "title": "Exception state", "type": "Informational"}], "success": true}
